### ISSUE TITLE
EMOM Mode

### ISSUE THREAD

**Issue by kmaslowiec** [kmaslowiec/crossfit_trivia#13]
# CF definition:
> **EMOM** stands for “every minute on the minute.” So, for a given length of time, you perform a specific number of reps of a  
> movement (or movements) at the top of every new minute, then rest until the next minute starts again.

# Mode rules:
- [x] Teaching mode
- [x] If the user answers wrong 'No Rep' fragment is displayed
- [x] The skip button is available after 45 s 
- [x] (Optional) It will count how long took the user to answer the question minus one minute
- [x] If the answer is correct the user can choose to see 'No Rep' fragment or go to the next question
- [ ] Learning last 15 minutes  
- [ ] (Optional) Record wrong answers and only those are displayed

**//TODO** 
- [x] [Fragment look](https://github.com/kmaslowiec/crossfit_trivia/issues/15)
- [ ] [Fragment logic](https://github.com/kmaslowiec/crossfit_trivia/issues/14)
